version: "3.8"
services:
  app:
    image: hello_compose:latest
    ports:
      # Assign the container's port 3000 to any open port on the host
      # To use a specific port, use the format: "<host_port>:<container_port>"
      - "3000"
    depends_on:
      - db
      - cache
    environment:
      - DB_URL=mariadb://root:my-secret-pw@db/phonebook
      - REDIS_URL=redis://cache
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=phonebook
    volumes:
      - phonebook_data:/var/lib/mysql
  cache:
    image: redis:latest

volumes:
  phonebook_data:
