services: 
  app: 
    build: ./

  database:
    image: postgres:16  
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    ports: 
      - 5432:5432
    volumes: 
      - database:/var/lib/postgresql/data

volumes:
  database:
